<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject></StartupObject>
	<AssemblyName>Ignis.Frontend</AssemblyName>
    <RootNamespace>Ignis.Frontend</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\Images\" />
    <Folder Include="Assets\Icon\" />
    <Folder Include="Features\Auth\Register\" />
  </ItemGroup>

</Project>
